"""Stable SUGAR core for repeatable public-source collection and analysis."""

from .collector_registry import (
    COLLECTORS,
    CollectorCapabilities,
    CollectorRequest,
    CollectorSpec,
    collect_registered_comments,
    collect_registered_source,
    collector_capabilities,
    fetch_registered_item,
    get_collector,
)
from .harvest import (
    HarvestConfig,
    HarvestStore,
    HarvestTask,
    build_harvest_tasks,
    rate_limit_wait_seconds,
)
from .lineage import (
    LINEAGE_SCHEMA_VERSION,
    build_lineage_index,
    load_dataset_metadata,
    load_lineage_index,
    provenance_document,
    save_lineage_index,
    validate_lineage_index,
)
from .models import COLLECTOR_VERSION, SCHEMA_VERSION, PostRecord
from .observation_storage import load_observations, observations_to_frame, save_observations
from .observations import (
    OBSERVATION_SCHEMA_VERSION,
    EvidenceReference,
    ObservationLocation,
    ResearchObservation,
    SpatialMatch,
    observation_from_post,
    observations_from_posts,
)
from .requirement_compiler import (
    RESEARCH_STRATEGY_SCHEMA_VERSION,
    RESEARCH_STRATEGY_WORKFLOW,
    CompiledResearchStrategy,
    MissingDimension,
    ResearchDimension,
    SourceSpan,
    StrategyConcept,
    build_search_plan_from_strategy,
    compile_requirement_deterministically,
    enrich_strategy_with_llm,
    load_research_strategy,
    save_research_strategy,
)
from .service import run_analysis, run_harvest, run_map, run_overlap, run_search
from .source_conflicts import (
    SOURCE_AUTHORITY_TYPES,
    SOURCE_CONFLICT_STATUSES,
    SOURCE_CONFLICT_TYPES,
    SOURCE_FRESHNESS_STATES,
    SourceClaim,
    SourceConflict,
    load_source_conflicts,
    save_source_conflicts,
    source_conflict_summary,
    source_conflict_to_dict,
    source_conflicts_to_dicts,
)
from .spatial import (
    DEFAULT_DISTANCE_BANDS_KM,
    ReferencePoint,
    SpatialOverlapConfig,
    analyze_spatial_overlap,
    distance_band,
    haversine_km,
    reference_points_from_frame,
)
from .triage import (
    DEFAULT_PROJECT_CONTEXT,
    GroundedEvidence,
    TriageResult,
    observation_from_triage,
    parse_triage_result,
    triage_post,
    triage_posts,
)
from .triage_io import load_post_records, post_record_from_mapping, triage_dataset
from .weibo_investigation import (
    WeiboInvestigation,
    build_weibo_insights,
    collect_weibo_reposts,
    collect_weibo_user_timeline,
    fetch_weibo_seed_status,
    investigate_weibo_seed,
    parse_weibo_seed,
    render_weibo_brief,
    save_weibo_investigation,
)
from .workspace import (
    ArtifactRecord,
    SugarWorkspace,
    WorkspaceManifest,
    open_workspace,
)

__all__ = [
    "PostRecord",
    "SCHEMA_VERSION",
    "COLLECTOR_VERSION",
    "CollectorCapabilities",
    "CollectorRequest",
    "CollectorSpec",
    "COLLECTORS",
    "get_collector",
    "collector_capabilities",
    "collect_registered_source",
    "fetch_registered_item",
    "collect_registered_comments",
    "HarvestConfig",
    "HarvestStore",
    "HarvestTask",
    "build_harvest_tasks",
    "rate_limit_wait_seconds",
    "LINEAGE_SCHEMA_VERSION",
    "build_lineage_index",
    "save_lineage_index",
    "load_lineage_index",
    "validate_lineage_index",
    "load_dataset_metadata",
    "provenance_document",
    "ResearchObservation",
    "ObservationLocation",
    "EvidenceReference",
    "SpatialMatch",
    "OBSERVATION_SCHEMA_VERSION",
    "observation_from_post",
    "observations_from_posts",
    "observations_to_frame",
    "save_observations",
    "load_observations",
    "RESEARCH_STRATEGY_SCHEMA_VERSION",
    "RESEARCH_STRATEGY_WORKFLOW",
    "SourceSpan",
    "StrategyConcept",
    "ResearchDimension",
    "MissingDimension",
    "CompiledResearchStrategy",
    "compile_requirement_deterministically",
    "enrich_strategy_with_llm",
    "build_search_plan_from_strategy",
    "save_research_strategy",
    "load_research_strategy",
    "SourceClaim",
    "SourceConflict",
    "SOURCE_AUTHORITY_TYPES",
    "SOURCE_FRESHNESS_STATES",
    "SOURCE_CONFLICT_TYPES",
    "SOURCE_CONFLICT_STATUSES",
    "source_conflict_to_dict",
    "source_conflicts_to_dicts",
    "source_conflict_summary",
    "save_source_conflicts",
    "load_source_conflicts",
    "DEFAULT_DISTANCE_BANDS_KM",
    "ReferencePoint",
    "SpatialOverlapConfig",
    "analyze_spatial_overlap",
    "distance_band",
    "haversine_km",
    "reference_points_from_frame",
    "GroundedEvidence",
    "TriageResult",
    "DEFAULT_PROJECT_CONTEXT",
    "parse_triage_result",
    "triage_post",
    "triage_posts",
    "observation_from_triage",
    "post_record_from_mapping",
    "load_post_records",
    "triage_dataset",
    "run_search",
    "run_harvest",
    "run_map",
    "run_overlap",
    "run_analysis",
    "WeiboInvestigation",
    "parse_weibo_seed",
    "fetch_weibo_seed_status",
    "collect_weibo_reposts",
    "collect_weibo_user_timeline",
    "build_weibo_insights",
    "investigate_weibo_seed",
    "render_weibo_brief",
    "save_weibo_investigation",
    "WorkspaceManifest",
    "ArtifactRecord",
    "SugarWorkspace",
    "open_workspace",
]

__version__ = "1.3.0"
